class SuraModel {
  
  String suraNameEn;
  String suraNameAr;
  String versesNum;
  String suraIndex;

  SuraModel({
    required this.suraNameEn,
    required this.suraNameAr,
    required this.versesNum,
    required this.suraIndex,
  });

  
static List<SuraModel> suras = [
  SuraModel(suraIndex: "1", suraNameAr: "الفاتحه", suraNameEn: "Al-Fatiha", versesNum: "7"),
  SuraModel(suraIndex: "2", suraNameAr: "البقرة", suraNameEn: "Al-Baqarah", versesNum: "286"),
  SuraModel(suraIndex: "3", suraNameAr: "آل عمران", suraNameEn: "Aal-E-Imran", versesNum: "200"),
  SuraModel(suraIndex: "4", suraNameAr: "النساء", suraNameEn: "An-Nisa'", versesNum: "176"),
  SuraModel(suraIndex: "5", suraNameAr: "المائدة", suraNameEn: "Al-Ma'idah", versesNum: "120"),
  SuraModel(suraIndex: "6", suraNameAr: "الأنعام", suraNameEn: "Al-An'am", versesNum: "165"),
  SuraModel(suraIndex: "7", suraNameAr: "الأعراف", suraNameEn: "Al-A'raf", versesNum: "206"),
  SuraModel(suraIndex: "8", suraNameAr: "الأنفال", suraNameEn: "Al-Anfal", versesNum: "75"),
  SuraModel(suraIndex: "9", suraNameAr: "التوبة", suraNameEn: "At-Tawbah", versesNum: "129"),
  SuraModel(suraIndex: "10", suraNameAr: "يونس", suraNameEn: "Yunus", versesNum: "109"),
  SuraModel(suraIndex: "11", suraNameAr: "هود", suraNameEn: "Hud", versesNum: "123"),
  SuraModel(suraIndex: "12", suraNameAr: "يوسف", suraNameEn: "Yusuf", versesNum: "111"),
  SuraModel(suraIndex: "13", suraNameAr: "الرعد", suraNameEn: "Ar-Ra'd", versesNum: "43"),
  SuraModel(suraIndex: "14", suraNameAr: "إبراهيم", suraNameEn: "Ibrahim", versesNum: "52"),
  SuraModel(suraIndex: "15", suraNameAr: "الحجر", suraNameEn: "Al-Hijr", versesNum: "99"),
  SuraModel(suraIndex: "16", suraNameAr: "النحل", suraNameEn: "An-Nahl", versesNum: "128"),
  SuraModel(suraIndex: "17", suraNameAr: "الإسراء", suraNameEn: "Al-Isra", versesNum: "111"),
  SuraModel(suraIndex: "18", suraNameAr: "الكهف", suraNameEn: "Al-Kahf", versesNum: "110"),
  SuraModel(suraIndex: "19", suraNameAr: "مريم", suraNameEn: "Maryam", versesNum: "98"),
  SuraModel(suraIndex: "20", suraNameAr: "طه", suraNameEn: "Ta-Ha", versesNum: "135"),
  SuraModel(suraIndex: "21", suraNameAr: "الأنبياء", suraNameEn: "Al-Anbiya", versesNum: "112"),
  SuraModel(suraIndex: "22", suraNameAr: "الحج", suraNameEn: "Al-Hajj", versesNum: "78"),
  SuraModel(suraIndex: "23", suraNameAr: "المؤمنون", suraNameEn: "Al-Mu'minun", versesNum: "118"),
  SuraModel(suraIndex: "24", suraNameAr: "النّور", suraNameEn: "An-Nur", versesNum: "64"),
  SuraModel(suraIndex: "25", suraNameAr: "الفرقان", suraNameEn: "Al-Furqan", versesNum: "77"),
  SuraModel(suraIndex: "26", suraNameAr: "الشعراء", suraNameEn: "Ash-Shu'ara", versesNum: "227"),
  SuraModel(suraIndex: "27", suraNameAr: "النّمل", suraNameEn: "An-Naml", versesNum: "93"),
  SuraModel(suraIndex: "28", suraNameAr: "القصص", suraNameEn: "Al-Qasas", versesNum: "88"),
  SuraModel(suraIndex: "29", suraNameAr: "العنكبوت", suraNameEn: "Al-Ankabut", versesNum: "69"),
  SuraModel(suraIndex: "30", suraNameAr: "الرّوم", suraNameEn: "Ar-Rum", versesNum: "60"),
  SuraModel(suraIndex: "31", suraNameAr: "لقمان", suraNameEn: "Luqman", versesNum: "34"),
  SuraModel(suraIndex: "32", suraNameAr: "السجدة", suraNameEn: "As-Sajda", versesNum: "30"),
  SuraModel(suraIndex: "33", suraNameAr: "الأحزاب", suraNameEn: "Al-Ahzab", versesNum: "73"),
  SuraModel(suraIndex: "34", suraNameAr: "سبأ", suraNameEn: "Saba", versesNum: "54"),
  SuraModel(suraIndex: "35", suraNameAr: "فاطر", suraNameEn: "Fatir", versesNum: "45"),
  SuraModel(suraIndex: "36", suraNameAr: "يس", suraNameEn: "Ya-Sin", versesNum: "83"),
  SuraModel(suraIndex: "37", suraNameAr: "الصافات", suraNameEn: "As-Saffat", versesNum: "182"),
  SuraModel(suraIndex: "38", suraNameAr: "ص", suraNameEn: "Sad", versesNum: "88"),
  SuraModel(suraIndex: "39", suraNameAr: "الزمر", suraNameEn: "Az-Zumar", versesNum: "75"),
  SuraModel(suraIndex: "40", suraNameAr: "غافر", suraNameEn: "Ghafir", versesNum: "85"),
  SuraModel(suraIndex: "41", suraNameAr: "فصّلت", suraNameEn: "Fussilat", versesNum: "54"),
  SuraModel(suraIndex: "42", suraNameAr: "الشورى", suraNameEn: "Ash-Shura", versesNum: "53"),
  SuraModel(suraIndex: "43", suraNameAr: "الزخرف", suraNameEn: "Az-Zukhruf", versesNum: "89"),
  SuraModel(suraIndex: "44", suraNameAr: "الدّخان", suraNameEn: "Ad-Dukhan", versesNum: "59"),
  SuraModel(suraIndex: "45", suraNameAr: "الجاثية", suraNameEn: "Al-Jathiya", versesNum: "37"),
  SuraModel(suraIndex: "46", suraNameAr: "الأحقاف", suraNameEn: "Al-Ahqaf", versesNum: "35"),
  SuraModel(suraIndex: "47", suraNameAr: "محمد", suraNameEn: "Muhammad", versesNum: "38"),
  SuraModel(suraIndex: "48", suraNameAr: "الفتح", suraNameEn: "Al-Fath", versesNum: "29"),
  SuraModel(suraIndex: "49", suraNameAr: "الحجرات", suraNameEn: "Al-Hujurat", versesNum: "18"),
  SuraModel(suraIndex: "50", suraNameAr: "ق", suraNameEn: "Qaf", versesNum: "45"),
  SuraModel(suraIndex: "51", suraNameAr: "الذاريات", suraNameEn: "Adh-Dhariyat", versesNum: "60"),
  SuraModel(suraIndex: "52", suraNameAr: "الطور", suraNameEn: "At-Tur", versesNum: "49"),
  SuraModel(suraIndex: "53", suraNameAr: "النجم", suraNameEn: "An-Najm", versesNum: "62"),
  SuraModel(suraIndex: "54", suraNameAr: "القمر", suraNameEn: "Al-Qamar", versesNum: "55"),
  SuraModel(suraIndex: "55", suraNameAr: "الرحمن", suraNameEn: "Ar-Rahman", versesNum: "78"),
  SuraModel(suraIndex: "56", suraNameAr: "الواقعة", suraNameEn: "Al-Waqi'a", versesNum: "96"),
  SuraModel(suraIndex: "57", suraNameAr: "الحديد", suraNameEn: "Al-Hadid", versesNum: "29"),
  SuraModel(suraIndex: "58", suraNameAr: "المجادلة", suraNameEn: "Al-Mujadila", versesNum: "22"),
  SuraModel(suraIndex: "59", suraNameAr: "الحشر", suraNameEn: "Al-Hashr", versesNum: "24"),
  SuraModel(suraIndex: "60", suraNameAr: "الممتحنة", suraNameEn: "Al-Mumtahina", versesNum: "13"),
  SuraModel(suraIndex: "61", suraNameAr: "الصف", suraNameEn: "As-Saff", versesNum: "14"),
  SuraModel(suraIndex: "62", suraNameAr: "الجمعة", suraNameEn: "Al-Jumu'a", versesNum: "11"),
  SuraModel(suraIndex: "63", suraNameAr: "المنافقون", suraNameEn: "Al-Munafiqun", versesNum: "11"),
  SuraModel(suraIndex: "64", suraNameAr: "التغابن", suraNameEn: "At-Taghabun", versesNum: "18"),
  SuraModel(suraIndex: "65", suraNameAr: "الطلاق", suraNameEn: "At-Talaq", versesNum: "12"),
  SuraModel(suraIndex: "66", suraNameAr: "التحريم", suraNameEn: "At-Tahrim", versesNum: "12"),
  SuraModel(suraIndex: "67", suraNameAr: "الملك", suraNameEn: "Al-Mulk", versesNum: "30"),
  SuraModel(suraIndex: "68", suraNameAr: "القلم", suraNameEn: "Al-Qalam", versesNum: "52"),
  SuraModel(suraIndex: "69", suraNameAr: "الحاقة", suraNameEn: "Al-Haqqah", versesNum: "52"),
  SuraModel(suraIndex: "70", suraNameAr: "المعارج", suraNameEn: "Al-Ma'arij", versesNum: "44"),
  SuraModel(suraIndex: "71", suraNameAr: "نوح", suraNameEn: "Nuh", versesNum: "28"),
  SuraModel(suraIndex: "72", suraNameAr: "الجن", suraNameEn: "Al-Jinn", versesNum: "28"),
  SuraModel(suraIndex: "73", suraNameAr: "المزّمّل", suraNameEn: "Al-Muzzammil", versesNum: "20"),
  SuraModel(suraIndex: "74", suraNameAr: "المدّثر", suraNameEn: "Al-Muddathir", versesNum: "56"),
  SuraModel(suraIndex: "75", suraNameAr: "القيامة", suraNameEn: "Al-Qiyamah", versesNum: "40"),
  SuraModel(suraIndex: "76", suraNameAr: "الإنسان", suraNameEn: "Al-Insan", versesNum: "31"),
  SuraModel(suraIndex: "77", suraNameAr: "المرسلات", suraNameEn: "Al-Mursalat", versesNum: "50"),
  SuraModel(suraIndex: "78", suraNameAr: "النبأ", suraNameEn: "An-Naba'", versesNum: "40"),
  SuraModel(suraIndex: "79", suraNameAr: "النازعات", suraNameEn: "An-Nazi'at", versesNum: "46"),
  SuraModel(suraIndex: "80", suraNameAr: "عبس", suraNameEn: "Abasa", versesNum: "42"),
  SuraModel(suraIndex: "81", suraNameAr: "التكوير", suraNameEn: "At-Takwir", versesNum: "29"),
  SuraModel(suraIndex: "82", suraNameAr: "الإنفطار", suraNameEn: "Al-Infitar", versesNum: "19"),
  SuraModel(suraIndex: "83", suraNameAr: "المطفّفين", suraNameEn: "Al-Mutaffifin", versesNum: "36"),
  SuraModel(suraIndex: "84", suraNameAr: "الإنشقاق", suraNameEn: "Al-Inshiqaq", versesNum: "25"),
  SuraModel(suraIndex: "85", suraNameAr: "البروج", suraNameEn: "Al-Buruj", versesNum: "22"),
  SuraModel(suraIndex: "86", suraNameAr: "الطارق", suraNameEn: "At-Tariq", versesNum: "17"),
  SuraModel(suraIndex: "87", suraNameAr: "الأعلى", suraNameEn: "Al-A'la", versesNum: "19"),
  SuraModel(suraIndex: "88", suraNameAr: "الغاشية", suraNameEn: "Al-Ghashiyah", versesNum: "26"),
  SuraModel(suraIndex: "89", suraNameAr: "الفجر", suraNameEn: "Al-Fajr", versesNum: "30"),
  SuraModel(suraIndex: "90", suraNameAr: "البلد", suraNameEn: "Al-Balad", versesNum: "20"),
  SuraModel(suraIndex: "91", suraNameAr: "الشمس", suraNameEn: "Ash-Shams", versesNum: "15"),
  SuraModel(suraIndex: "92", suraNameAr: "الليل", suraNameEn: "Al-Lail", versesNum: "21"),
  SuraModel(suraIndex: "93", suraNameAr: "الضحى", suraNameEn: "Ad-Duha", versesNum: "11"),
  SuraModel(suraIndex: "94", suraNameAr: "الشرح", suraNameEn: "Ash-Sharh", versesNum: "8"),
  SuraModel(suraIndex: "95", suraNameAr: "التين", suraNameEn: "At-Tin", versesNum: "8"),
  SuraModel(suraIndex: "96", suraNameAr: "العلق", suraNameEn: "Al-Alaq", versesNum: "19"),
  SuraModel(suraIndex: "97", suraNameAr: "القدر", suraNameEn: "Al-Qadr", versesNum: "5"),
  SuraModel(suraIndex: "98", suraNameAr: "البينة", suraNameEn: "Al-Bayyina", versesNum: "8"),
  SuraModel(suraIndex: "99", suraNameAr: "الزلزلة", suraNameEn: "Az-Zalzalah", versesNum: "8"),
  SuraModel(suraIndex: "100", suraNameAr: "العاديات", suraNameEn: "Al-Adiyat", versesNum: "11"),
  SuraModel(suraIndex: "101", suraNameAr: "القارعة", suraNameEn: "Al-Qari'a", versesNum: "11"),
  SuraModel(suraIndex: "102", suraNameAr: "التكاثر", suraNameEn: "At-Takathur", versesNum: "8"),
  SuraModel(suraIndex: "103", suraNameAr: "العصر", suraNameEn: "Al-Asr", versesNum: "3"),
  SuraModel(suraIndex: "104", suraNameAr: "الهمزة", suraNameEn: "Al-Humazah", versesNum: "9"),
  SuraModel(suraIndex: "105", suraNameAr: "الفيل", suraNameEn: "Al-Fil", versesNum: "5"),
  SuraModel(suraIndex: "106", suraNameAr: "قريش", suraNameEn: "Quraysh", versesNum: "4"),
  SuraModel(suraIndex: "107", suraNameAr: "الماعون", suraNameEn: "Al-Ma'un", versesNum: "7"),
  SuraModel(suraIndex: "108", suraNameAr: "الكوثر", suraNameEn: "Al-Kawthar", versesNum: "3"),
  SuraModel(suraIndex: "109", suraNameAr: "الكافرون", suraNameEn: "Al-Kafirun", versesNum: "6"),
  SuraModel(suraIndex: "110", suraNameAr: "النصر", suraNameEn: "An-Nasr", versesNum: "3"),
  SuraModel(suraIndex: "111", suraNameAr: "المسد", suraNameEn: "Al-Masad", versesNum: "5"),
  SuraModel(suraIndex: "112", suraNameAr: "الإخلاص", suraNameEn: "Al-Ikhlas", versesNum: "4"),
  SuraModel(suraIndex: "113", suraNameAr: "الفلق", suraNameEn: "Al-Falaq", versesNum: "5"),
  SuraModel(suraIndex: "114", suraNameAr: "الناس", suraNameEn: "An-Nas", versesNum: "6"),
];
}
